### model
model_name_or_path: saves/InternVL3-8B-Instruct/full/sft_mathcanvas
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: dpo
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
pref_beta: 0.1
pref_loss: sigmoid
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: mathcanvas_dpo
template: intern_vl
cutoff_len: 16384
max_samples: 20000
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/InternVL3-8B-Instruct/full/dpo_mathcanvas
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: wandb

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 5.0e-7
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
